routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('homePage');
});

Route::resource('login', 'LogController');
Route::resource('admin', 'adminController');
Route::resource('product', 'productosController');
Route::resource('reportes', 'reportesController');
Route::get('logout','LogController@logout');

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    protected $fillable = [
        'reference','brand','model','type', 'quantity','color','entryDate','importedFrom'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'typeDocument','document','name','lastName', 'password','position'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($valor){
        if(!empty($valor)){
            $this->attributes['password'] = \Hash::make($valor);
        }
        
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests;
use App\HTTP\Requests\UserCreateRequest;
use App\HTTP\Requests\UserUpdateRequest;
use App\User;
use App\Products;
use Session;
use Redirect; 
use Illuminate\Http\Request;

class AdminController extends Controller
{  
    // metodo index Administrador
    public function index(){
        //Retorna a vista index blade
        return view('admin.index');
    }
    //metodo crear usuarios
    public function create(){
        return view('admin.createUser');
    }

    //Metodo para almacenar datos
    public function store(UserCreateRequest $request){
        \App\User::create([
        'typeDocument'=>$request['typeDocument'],
        'document'=>$request['document'],
        'name'=>$request['name'],
        'lastName'=>$request['lastName'],
        'password'=>$request['password'],
        'position'=>$request['position'],
        ]);
        return redirect('/admin/show')->with('message','Usuario Añadido Correctamente');
    }

    //metodo que muestra los usuarios creados
    public function show(){
        $users = \App\User::paginate(5);
        return view('admin.consultarUsuarios',compact('users'));
    }

    // metodo para edita datos 
    public function edit($id){
        $users = User::find($id);
        return view('admin.edit',['users'=>$users]);
    }

    // metodo para actualizar los datos 
    public function update($id, UserUpdateRequest $request){
        $users= User::find($id);
        $users->fill($request->all());
        $users->save();
        Session::flash('message','Usuario Editado correctamente');
        return Redirect::to('/admin/show');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LogController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests;
use Auth;
use Session;
use Redirect;
use App\HTTP\Requests\UserLogRequest;
use Illuminate\Http\Request;

class LogController extends Controller
{
    public function index(){
        return view('login');
    }

    public function logout(){
        Auth::logout();
        return Redirect::to('/');
    }
    public function store( UserLogRequest $request){
       if (Auth::attempt(['document' => $request['document'],'password'=>$request['password'],'position'=>'Administrador']))
        {
            return Redirect::to('admin');

        }else if(Auth::attempt(['document' => $request['document'],'password'=>$request['password'],'position'=>'Operario'])){
            return Redirect::to('product');
        }else{ 
            Session::flash('message-error', "datos son Incorrectos");
            return Redirect::to('login'); 
        }
    }

        public function show(){

        }
    
    }

app/Http/Controllers/ProductosController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests;
use App\HTTP\Requests\ProductsCreateRequest;
use App\HTTP\Requests\ProductsUpdateRequest;
use App\Products;
use Session;
use Redirect; 
use Illuminate\Http\Request;

class ProductosController extends Controller
{
    public function index(){
        return view('operario.index');
    }
    public function create(){
        return view('admin.crearProductos');
    }
    public function store(ProductsCreateRequest $request){
        \App\Products::create([
        'reference'=>$request['reference'],
        'brand'=>$request['brand'],
        'model'=>$request['model'],
        'type'=>$request['type'],
        'quantity'=>$request['quantity'],
        'color'=>$request['color'],
        'entryDate'=>$request['entryDate'],
        'importedFrom'=>$request['importedFrom'],
        ]);
        return redirect('/product/show')->with('message','Prducto Añadido Correctamente');
    }
    public function show(){
        $products = \App\Products::all();
        return view('operario.consultarProductos',compact('products'));

    }

    public function edit($id){
        $products = \App\Products::find($id);
        return view('operario.editarProductos',['products'=>$products]);
    
        }

        public function update($id,ProductsUpdateRequest $request){
            $products = \App\Products::find($id);
            $products->fill($request->all());
            $products->save();
            Session::flash('message','Datos Editados correctamente');
            return Redirect::to('/product/show');
          }
          
        }

app/Http/Controllers/ReportesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ReportesController extends Controller
{   
    //metodo para crear reportes
    public function create(){
    return view('reportes.error');
    }
    //metodo para  mostrar reportes registrados 
    public function show(){
    return view('reportes.error');
    }
    //metodo para almacenar datos 
    public function store(){
    
    }
    //metodo para desabilitar reportes
    public function destroy(){
    return view('reportes.error');
    }

}

resources/views/admin/consultarUsuarios.blade.php
@extends('plantillas.layout')

@section('contenido')
<div class="container-fluid">
    @if(Session::has('message'))
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" arial-label="close"><span aria-hidden="true">&times;</span></button>
      {{Session::get('message')}}
      </div>
    @endif
    <h1>Consultar Usuarios</h1>
    <hr> 
  </div>
  <!-- /.container-fluid-->
  <div class="content-fluid">
  </div>
  @include('formsAdmin.consultarUsuarios')
@stop

resources/views/admin/crearProductos.blade.php
@extends('plantillas.layout')
@section('contenido')
<div class="container-fluid">
    <h1>Añadir Productos</h1>
    <hr> 
  </div>
  <!-- /.container-fluid-->
  <div class="content-fluid">
      @include('alerts.request')
  </div>
<div class="container">
    
        {!!Form::open(['route'=>'product.store','method'=>'POST'])!!}  
        @include('formsProductos.createProductos')
    
       
</div>

<div class="col-md-12">
{!! Form::submit('Añadir Producto', ['class'=>'btn btn-primary','style'=>'margin-top:2%; margin-left:45%;']) !!}
</div>

{!! Form::close() !!}

@stop

resources/views/admin/createUser.blade.php
@extends('plantillas.layout')
@section('contenido')
@include('alerts.request')
<div class="container-fluid">
    <h1>Añadir usuarios</h1>
    <hr> 
  </div>
  <!-- /.container-fluid-->
  <div class="content-fluid">
  </div>
<div class="container">
    
        {!!Form::open(['route'=>'admin.store','method'=>'POST'])!!}
        @include('formsAdmin.createUser')
   
</div>

<div class="col-md-12">
{!! Form::submit('Añadir Usuario', ['class'=>'btn btn-primary','style'=>'margin-top:2%; margin-left:45%;']) !!}
</div>

{!! Form::close() !!}

@stop

resources/views/admin/edit.blade.php
@extends('plantillas.layout')
@section('contenido')
@include('alerts.request')
<div class="container-fluid">
    <h1>Editar usuarios</h1>
    <hr> 
  </div>
  <!-- /.container-fluid-->
  <div class="content-fluid">
  </div>
  <div class="container">
        {!!Form::model($users, ['route' => ['admin.update', $users->id],'method'=>'PUT'])!!}
        @include('formsAdmin.edit')
       
</div>
<div class="col-md-12">
{!! Form::submit('Añadir Usuario', ['class'=>'btn btn-primary','style'=>'margin-top:2%; margin-left:45%;']) !!}
</div>

{!! Form::close() !!}
@stop

resources/views/admin/index.blade.php
@extends('plantillas.layout')
@section('contenido')
<div class="container-fluid">
        <h1 class="title">Inicio</h1>
        <hr> 
      </div>
      <!-- /.container-fluid-->
      <div class="content-fluid">
      </div>
<div class="container">
    <div class="col-md-12">
        <h2>Bienvenido a SAGI</h2>
    </div>
    <div class="col-md-12">
        <div class="row">
                <div class="col-md-6">
                        <i class="fa fa-fw fa-group"style="font-size:140px; margin:5% 1% 3% 30%;"></i>
                        <h4 class="text-center">Añadir Usuarios</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis debitis suscipit voluptatem dolor explicabo quas nostrum numquam nihil inventore eos asperiores dolorem est maxime ducimus autem, reprehenderit perspiciatis? Nemo, velit?</p>
                       
                </div>
                <div class="col-md-6">
                        <i class="fa fa-fw fa-th-large"style="font-size:140px; margin:5% 1% 3% 30%;"></i>
                        <h4 class="text-center">Añadir Productos</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis debitis suscipit voluptatem dolor explicabo quas nostrum numquam nihil inventore eos asperiores dolorem est maxime ducimus autem, reprehenderit perspiciatis? Nemo, velit?</p>
                </div>
        </div>
        <div class="row">
                <div class="col-md-6">
                        <i class="fa fa-fw fa-area-chart"style="font-size:140px; margin:5% 1% 3% 30%;"></i>
                        <h4 class="text-center">Consultar</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis debitis suscipit voluptatem dolor explicabo quas nostrum numquam nihil inventore eos asperiores dolorem est maxime ducimus autem, reprehenderit perspiciatis? Nemo, velit?</p>
                </div>
                <div class="col-md-6">
                        <i class="fa fa-fw fa-area-chart"style="font-size:140px; margin:5% 1% 3% 30%;"></i>
                        <h4 class="text-center">Reportes</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis debitis suscipit voluptatem dolor explicabo quas nostrum numquam nihil inventore eos asperiores dolorem est maxime ducimus autem, reprehenderit perspiciatis? Nemo, velit?</p>
                </div>
        </div>
        


    </div>
</div>
@stop

resources/views/alerts/errors.blade.php
@if(Session::has('message-error'))
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" arial-label="close"><span aria-hidden="true">&times;</span></button>
    {{Session::get('message-error')}}
</div>


@endif

resources/views/alerts/request.blade.php
@if(count($errors)> 0)
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" arial-label="close"><span aria-hidden="true">&times;</span></button>
    <ul>
        @foreach($errors->all() as $error)
        <li style="text-decoration:none;">
              {!!$error!!}
        </li>
  
        @endforeach
    </ul>
  </div>
 
@endif

resources/views/alerts/success.blade.php
@if(Session::has('message'))
<div class="alert alert-successs" role="alert">
    <button type="button" class="close" data-dismiss="alert" arial-label="close"><span aria-hidden="true">&times;</span></button>
</div>
{{Session::get('message')}}

@endif

resources/views/formsAdmin/consultarUsuarios.blade.php
<table class="table table-hover">
    <thead>
    <th>Tipo Documento</th>
    <th>Documento</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Cargo</th>
    <th>Operaciones</th>
    </thead>
    @foreach($users as $user)
    <tbody>
    <td>{{$user->typeDocument}} </td>
    <td>{{$user->document}} </td>
    <td>{{$user->name}} </td>
    <td>{{$user->lastName}}</td>
    <td>{{$user->position}}</td>
    <td>{!! link_to_route('admin.edit', $title = 'editar', $parameters = $user->id, $attributes = ['class'=>'btn btn-success']) !!}</td>
    </tbody>
    @endforeach
    </table>
    {{ $users->links() }}

resources/views/formsAdmin/createUser.blade.php
<div class="row">
    <div class="col-md-6">
        {!! Form::label('typeDocument','Tipo Documento') !!}   
        {!! Form::select('typeDocument',[
            'documents' =>['Seleccione...','Cedula','pasaporte Extranjería']
        ],'Seleccione...', ['class'=>'form-control']) !!}
        
    </div>
    <div class="col-md-6">
        {!! Form::label('document','Numero Documento') !!}
        {!! Form::text('document',null,['class'=>'form-control']) !!} 
    </div>
</div>
<div class="row">
<div class="col-md-6">
{!! Form::label('name','Nombre') !!}
{!! Form::text('name',null,['class'=>'form-control']) !!}
</div>
<div class="col-md-6">
{!! Form::label('lastName','Apellido') !!}
{!! Form::text('lastName',null,['class'=>'form-control']) !!} 
</div>
</div>
<div class="row">
<div class="col-md-4">
{!! Form::label('password','Contraseña') !!}
{!!Form::password('password', ['class' => 'form-control']) !!}
</div>
<div class="col-md-4">
{!! Form::label('repeat','Repetir contraseña') !!} 
{!!Form::password('repeat', ['class' => 'form-control']) !!}
</div> 
<div class="col-md-4">
{!! Form::label('position','Cargo') !!} 
{!! Form::text('position',null,['class'=>'form-control']) !!}
</div> 
</div> 

resources/views/formsAdmin/edit.blade.php
<div class="row">
    <div class="col-md-6">
        {!! Form::label('typeDocument','Tipo Documento') !!}   
        {!! Form::select('typeDocument',[
            'documents' =>['Seleccione...','Cedula','pasaporte Extranjería']
        ],'Seleccione...', ['class'=>'form-control']) !!}
        
    </div>
    <div class="col-md-6">
        {!! Form::label('document','Numero Documento') !!}
        {!! Form::text('document',null,['class'=>'form-control']) !!} 
    </div>
</div>
<div class="row">
<div class="col-md-6">
{!! Form::label('name','Nombre') !!}
{!! Form::text('name',null,['class'=>'form-control']) !!}
</div>
<div class="col-md-6">
{!! Form::label('lastName','Apellido') !!}
{!! Form::text('lastName',null,['class'=>'form-control']) !!} 
</div>
</div>
<div class="row">
<div class="col-md-4">
{!! Form::label('password','Contraseña') !!}
{!!Form::password('password', ['class' => 'form-control']) !!}
</div>
<div class="col-md-4">
{!! Form::label('repeat','Repetir contraseña') !!} 
{!!Form::password('repeat', ['class' => 'form-control']) !!}
</div> 
<div class="col-md-4">
{!! Form::label('position','Cargo') !!} 
{!! Form::text('position',null,['class'=>'form-control']) !!}
</div> 
</div> 

resources/views/formsProductos/consultarProductos.blade.php
<table class="table table-hover">
    <thead>
    <th>Referencia</th>
    <th>Marca</th>
    <th>Modelo</th>
    <th>Tipo</th>
    <th>Cantidad</th>
    <th>Color</th>
    <th>Fecha Ingreso</th>
    <th>Importado de</th>
    <th>Operaciones</th>
    </thead>
    @foreach($products as $product)
    <tbody>
        <td>{{$product->reference}} </td>
        <td>{{$product->brand}} </td>
        <td>{{$product->model}} </td>
        <td>{{$product->type}} </td>
        <td>{{$product->quantity}} </td>
        <td>{{$product->color}} </td>
        <td>{{$product->entryDate}} </td>
        <td>{{$product->importedFrom}}</td>
        <td>  {!! link_to_route('product.edit', $title = 'editar', $parameters = $product->id, $attributes = ['class'=>'btn btn-warning']) !!}</td>
    </tbody>
    @endforeach
    </table>

resources/views/formsProductos/createProductos.blade.php
<div class="row">
    <div class="col-md-6">
        {!! Form::label('reference','Referencia') !!}
        {!! Form::text('reference',null, ['class'=>'form-control']) !!}      
    </div>
    <div class="col-md-6">
        {!! Form::label('brand','Marca') !!}
        {!! Form::text('brand',null,['class'=>'form-control']) !!} 
    </div>
</div>

<div class="row">
        <div class="col-md-6">
            {!! Form::label('model','Modelo') !!}
            {!! Form::text('model',null, ['class'=>'form-control']) !!}      
        </div>
        <div class="col-md-6">
            {!! Form::label('type','Tipo') !!}
            {!! Form::text('type',null,['class'=>'form-control']) !!} 
        </div>
</div>

<div class="row">
        <div class="col-md-6">
            {!! Form::label('quantity','Cantidad') !!}
            {!! Form::text('quantity',null, ['class'=>'form-control']) !!}      
        </div>
        <div class="col-md-6">
            {!! Form::label('color','Color') !!}
            {!! Form::text('color',null,['class'=>'form-control']) !!} 
        </div>
</div>
<div class="row">
        <div class="col-md-6">
            {!! Form::label('entryDate','Fecha Ingreso') !!}
            {!! Form::text('entryDate',null, ['class'=>'form-control']) !!}      
        </div>
        <div class="col-md-6">
            {!! Form::label('importedFrom','Importado de') !!}
            {!! Form::text('importedFrom',null,['class'=>'form-control']) !!} 
        </div>
</div>

resources/views/formsProductos/editarProductos.blade.php
<div class="row">
    <div class="col-md-6">
        {!! Form::label('reference','Referencia') !!}
        {!! Form::text('reference',null, ['class'=>'form-control']) !!}      
    </div>
    <div class="col-md-6">
        {!! Form::label('brand','Marca') !!}
        {!! Form::text('brand',null,['class'=>'form-control']) !!} 
    </div>
</div>

<div class="row">
        <div class="col-md-6">
            {!! Form::label('model','Modelo') !!}
            {!! Form::text('model',null, ['class'=>'form-control']) !!}      
        </div>
        <div class="col-md-6">
            {!! Form::label('type','Tipo') !!}
            {!! Form::text('type',null,['class'=>'form-control']) !!} 
        </div>
</div>

<div class="row">
        <div class="col-md-6">
            {!! Form::label('quantity','Cantidad') !!}
            {!! Form::text('quantity',null, ['class'=>'form-control']) !!}      
        </div>
        <div class="col-md-6">
            {!! Form::label('color','Color') !!}
            {!! Form::text('color',null,['class'=>'form-control']) !!} 
        </div>
</div>
<div class="row">
        <div class="col-md-6">
            {!! Form::label('entryDate','Fecha Ingreso') !!}
            {!! Form::text('entryDate',null, ['class'=>'form-control']) !!}      
        </div>
        <div class="col-md-6">
            {!! Form::label('importedFrom','Importado de') !!}
            {!! Form::text('importedFrom',null,['class'=>'form-control']) !!} 
        </div>
</div>

resources/views/login.blade.php
<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Login</title>
<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" >
{!!Html::style('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css')!!}
{!!Html::style('css/estilos.css')!!}
{!!Html::style('https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300')!!}
</head>

<body>
<div id="contenedor" class="degrade" >
  <div id="logo">{!!Html::image('img/logoSagi.png')!!}</div>
	@include('alerts.errors')
<div class="ContentForm">
		 	
			 {!! Form::open(['route'=>'login.store','method'=>'POST']) !!}
			 
		 		<div class="input-group input-group-lg">
					<span class="input-group-addon" id="sizing-addon1"><i class="glyphicon glyphicon-user"></i></span>
					{!! Form::text('document',null, ['class'=>'form-control','placeholder'=>'Usuario','aria-describedby'=>'sizing-addon1']) !!}
				</div>
				<br>
				<div class="input-group input-group-lg">
				  <span class="input-group-addon" id="sizing-addon1"><i class="glyphicon glyphicon-lock"></i></span>
					{!! Form::password('password', ['class'=>'form-control','placeholder'=>'*******','aria-describedby'=>'sizing-addon1']) !!}
				</div>
				<br>
				<button class="btn btn-lg btn-primary btn-block btn-signin" id="IngresoLog" type="submit">Iniciar Sesión</button>
		 	
			 {!! Form::close() !!}
			 @include('alerts.request')
		 </div>	
</div>
</body>
</html>

resources/views/operario/consultarProductos.blade.php
@extends('plantillas.layoutOperario')
@section('contenido')
<div class="container-fluid">
    @if(Session::has('message'))
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" arial-label="close"><span aria-hidden="true">&times;</span></button>
      {{Session::get('message')}}
      </div>
    @endif
    <h1>Consultar Productos Registrados</h1>
    <hr> 
  </div>
  <!-- /.container-fluid-->
  <div class="content-fluid">
  </div>
  @include('formsProductos.consultarProductos')

@stop

resources/views/operario/editarProductos.blade.php
@extends('plantillas.layoutOperario')
@section('contenido')
<div class="container-fluid">
    <h1>Añadir Productos</h1>
    <hr> 
  </div>
  <!-- /.container-fluid-->
  <div class="content-fluid">
        @include('alerts.request')
  </div>
<div class="container">
    
    {!!Form::model($products, ['route' => ['product.update', $products->id],'method'=>'PUT'])!!}
    @include('formsProductos.editarProductos')
        
</div>

<div class="col-md-12">
{!! Form::submit('Modificar Producto', ['class'=>'btn btn-primary','style'=>'margin-top:2%; margin-left:45%;']) !!}
</div>

{!! Form::close() !!}

@stop

resources/views/operario/index.blade.php
@extends('plantillas.layoutOperario')
@section('contenido')
<div class="container-fluid">
        <h1 class="title">Inicio</h1>
        <hr> 
      </div>
      <!-- /.container-fluid-->
      <div class="content-fluid">
      </div>
<div class="container">
    <div class="col-md-12">
        <h2>Bienvenido a SAGI</h2>
    </div>
    <div class="col-md-12">
        <div class="row">
                <div class="col-md-6">
                        <i class="fa fa-fw fa-group"style="font-size:140px; margin:5% 1% 3% 30%;"></i>
                        <h4 class="text-center">Añadir Usuarios</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis debitis suscipit voluptatem dolor explicabo quas nostrum numquam nihil inventore eos asperiores dolorem est maxime ducimus autem, reprehenderit perspiciatis? Nemo, velit?</p>
                       
                </div>
                <div class="col-md-6">
                        <i class="fa fa-fw fa-th-large"style="font-size:140px; margin:5% 1% 3% 30%;"></i>
                        <h4 class="text-center">Añadir Productos</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis debitis suscipit voluptatem dolor explicabo quas nostrum numquam nihil inventore eos asperiores dolorem est maxime ducimus autem, reprehenderit perspiciatis? Nemo, velit?</p>
                </div>
        </div>
        <div class="row">
                <div class="col-md-6">
                        <i class="fa fa-fw fa-area-chart"style="font-size:140px; margin:5% 1% 3% 30%;"></i>
                        <h4 class="text-center">Consultar</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis debitis suscipit voluptatem dolor explicabo quas nostrum numquam nihil inventore eos asperiores dolorem est maxime ducimus autem, reprehenderit perspiciatis? Nemo, velit?</p>
                </div>
                <div class="col-md-6">
                        <i class="fa fa-fw fa-area-chart"style="font-size:140px; margin:5% 1% 3% 30%;"></i>
                        <h4 class="text-center">Reportes</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis debitis suscipit voluptatem dolor explicabo quas nostrum numquam nihil inventore eos asperiores dolorem est maxime ducimus autem, reprehenderit perspiciatis? Nemo, velit?</p>
                </div>
        </div>
        


    </div>
</div>
@stop

resources/views/reportes/error.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error</title>
    {!!Html::style('vendor/bootstrap/css/bootstrap.min.css')!!}
    {!!Html::style('vendor/font-awesome/css/font-awesome.min.css')!!}
    {!!Html::style('https://fonts.googleapis.com/css?family=Poppins|Advent+Pro')!!}
    {!!Html::style('css/sb-admin.css')!!}
</head>
<body>
<div class="col-md-12">
    <div class="row">
            <p class="text-center" style="  font-family: 'Poppins', sans-serif; margin:1% 1% 2% 42%; font-size:70px; color:darkgray;">Wooops</p>
        </div>        
            <div class="row">
               {!!Html::image('img/map.png',"Imagen no encontrada", array('id' => 'principito', 'title' => 'El principito','style'=>'margin:0% 0% 0% 39%;'))!!}
            </div>
            <div class="row">
                <h1 style="  font-family: 'Advent Pro', sans-serif; margin:2% 1% 3% 30%; color:darkgray; ">No encontramos la pagina que buscas :-(</h1>
            </div>
            
           
    
</div>
</body>
</html>